---
# handlers file for 6_wordpress
- name: 'SetPermissionWpRedHat'
  file:
    path: "{{ site_folder }}/wordpress"
    state: directory
    owner: apache
    group: apache
    recurse: yes
  when: (ansible_facts['os_family'] == "RedHat")

- name: 'SetPermissionWpDebian'
  file:
    path: "{{ site_folder }}/wordpress"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  when: (ansible_facts['os_family'] == "Debian")