---
# handlers file for 6_wordpress
- name: 'RedHat : Configurando permissões da pasta do site.'
  file:
    path: "{{ site_folder }}/wordpress"
    state: directory
    owner: apache
    group: apache
    recurse: yes
  when: (ansible_facts['os_family'] == "RedHat")

- name: 'Debian : Configurando permissões da pasta do site.'
  file:
    path: "{{ site_folder }}/wordpress"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  when: (ansible_facts['os_family'] == "Debian")

- name: 'AnySO - Reinicialização Final'
  reboot: