---
# debian file for 4_apache2
- name: "Debian : Instalando o Apache2"
  apt:
    name:
    - apache2
    - libapache2-mod-fcgid
    - libapache2-mod-security2
    - libapache2-mod-evasive
    - openssl
    state: latest
  when: (ansible_facts['os_family'] == "Debian")
  notify:
    - 'Debian : Habilitando autoinicio do Apache2'

- name: "Debian : Habilitando os Módulos do Apache2"
  apache2_module:
    name: "{{ item }}"
  with_items:
    - actions
    - fcgid
    - alias
    - proxy_fcgi
    - headers
    - ssl
  when: (ansible_facts['os_family'] == "Debian")

- name: "Debian : Criando o Vhost do site"
  template:
    src: templates/site.conf
    dest: /etc/apache2/sites-available/{{site_log}}.conf
  when: (ansible_facts['os_family'] == "Debian")
  notify:
    - 'AnySO : Adicionando entrada do Vhost no arquivo Hosts'

- name: 'Debian : Habilitando o Vhost do Site'
  command: a2ensite {{site_log}}.conf
  when: (ansible_facts['os_family'] == "Debian")
  notify:
    - 'Debian : Desabilitando o Vhost Default do Apache2'
    - 'Debian : Reiniciando o serviço do Apache2'