---
# tasks file for 4_apache2

- name: 'Incluir Instalação Apache2 - Family Debian'
  include_tasks: debian.yml
  when: (ansible_facts['os_family'] == "Debian")

- name: "Incluir Instalação Apache2 - Family RedHat"
  include_tasks: redhat.yml
  when: (ansible_facts['os_family'] == "RedHat")