---
# redhat file for 4_apache2
- name: "RedHat : Instalando o Httpd"
  yum:
    name:
    - httpd
    - openssl
    state: latest
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - 'RedHat : Habilitando autoinicio do Httpd'

- name: "RedHat : Criando o diretório para o Vhost do Httpd"
  file:
    path: "/etc/httpd/vhost.d"
    state: directory
  when: (ansible_facts['os_family'] == "RedHat")

- name: "RedHat : Criando o Vhost do site"
  template:
    src: templates/site.conf
    dest: /etc/httpd/vhost.d/{{site_log}}.conf
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - 'AnySO : Adicionando entrada do Vhost no arquivo Hosts'
    - 'RedHat : Habilitando Vhost na configuraçao do Httpd'
    - 'RedHat : Reiniciando o serviço do Httpd'