---
# tasks file for 5_php
- name: "Debian : Instalando o PHP"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - php
      - php-fpm
      - php-cli
      - php-common
      - php-curl
      - php-mbstring
      - php-mysql
      - php-xml
      - php-gd
      - php-exif
    state: latest
  when: (ansible_facts['os_family'] == "Debian")