---
# tasks file for 3_mariadb

- name: 'Install MariaDB Server - Family RedHat'
  yum:
    update_cache: yes
    name:
      - mariadb-server
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: 'Install MariaDB Server - Family Debian'
  apt:
    update_cache: yes
    name:
      - mariadb-server
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: 'Start MariadDB Server'
  service:
    name: 'mariadb'
    state: started
    enabled: yes

- name: "Criando um banco de dados para ser utilizado pelo WordPress - Family Debian"
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    login_user: root
    state: present
  when: (ansible_facts[ 'os_family'] == "Debian")
  become: yes

- name: "Criando um banco de dados para ser utilizado pelo WordPress - Family RedHat"
  mysql_db:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_name }}"
    login_user: root
    state: present
  when: (ansible_facts[ 'os_family'] == "RedHat")
  become: yes

- name: "Create user with password, all database privileges in database - Family Debian"
  mysql_user:
    login_user: root
    host: localhost
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts[ 'os_family'] == "Debian")
  become: yes

- name: "Removes all anonymous user accounts - Family Debian"
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "Debian")

- name: "Create user with password, all database privileges in database - Family RedHat"
  mysql_user:
    login_user: root
    host: localhost
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts[ 'os_family'] == "RedHat")

- name: "Removes all anonymous user accounts - Family RedHat"
  mysql_user:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "RedHat")