---
# tasks file for 3_mariadb

- name: 'RedHat : Instalando o MariaDb Server'
  yum:
    update_cache: yes
    name:
      - mariadb-server
    state: present
  when: (ansible_facts['os_family'] == "RedHat")

- name: 'Debian : Instalando o MariaDb Server'
  apt:
    update_cache: yes
    name:
      - mariadb-server
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: 'AnySO : Iniciando o MariaDb Server'
  service:
    name: 'mariadb'
    state: started
    enabled: yes

- name: "Debian : Criando um Banco de Dados para ser utilizado pelo WordPress"
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    login_user: root
    state: present
  when: (ansible_facts[ 'os_family'] == "Debian")
  become: yes

- name: "RedHat : Criando um Banco de Dados para ser utilizado pelo WordPress"
  mysql_db:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_name }}"
    login_user: root
    state: present
  when: (ansible_facts[ 'os_family'] == "RedHat")
  become: yes

- name: "Debian : Criando o Usuário e seus Privilégios no Banco de Dados"
  mysql_user:
    login_user: root
    host: localhost
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts[ 'os_family'] == "Debian")
  become: yes

- name: "Debian : Removendo Usuários Anonymous do Banco de Dados"
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "Debian")

- name: "RedHat : Criando o Usuário e seus Privilégios no Banco de Dados"
  mysql_user:
    login_user: root
    host: localhost
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts[ 'os_family'] == "RedHat")

- name: "RedHat : Removendo Usuários Anonymous do Banco de Dados"
  mysql_user:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: ''
    host_all: yes
    state: absent
  when: (ansible_facts['os_family'] == "RedHat")