---
# tasks file for 1_python3
- name: 'Install Python3 - Family Debian'
  apt:
    pkg: "{{ item }}"
    update-cache: yes
    state: latest
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python3-pymysql
    - python3-mysqldb
    - default-libmysqlclient-dev
    - build-essential
    - pkg-config
  when: (ansible_facts['os_family'] == "Debian")

- name: 'Install Python3 - Family RedHat'
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-devel
    - python3-pip
    - mysql-devel
    - mysql-connector-python3
    - python3-mysql
    - pkgconfig
  when: (ansible_facts['os_family'] == "RedHat")
