---
# tasks file for 2_serversUtils
- name: 'AnySO : Configurando o Hostname dos servidores'
  hostname:
    name: "{{ hostname }}"
  notify:
    - 'AnySO : Limpando arquivo  Hosts do SO'
    - 'Debian : Modificando arquivo Hosts do SO'

- name: 'Debian : Instalando pacotes Uteis no servidor'
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - vim
      - htop
      - zip
      - unzip
      - wget
      - curl
      - nano
    state: latest
  when: (ansible_facts['os_family'] == "Debian")